# Generated by Django 4.1.5 on 2023-01-04 19:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                ("pokemon_id", models.AutoField(primary_key=True, serialize=False)),
                ("pokemon_name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=10)),
                ("fast_move", models.CharField(max_length=20)),
                ("charged_move", models.CharField(max_length=20)),
                ("created", models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                ("trainer_id", models.AutoField(primary_key=True, serialize=False)),
                ("trainer_name", models.CharField(max_length=50)),
                ("team", models.CharField(max_length=10)),
                (
                    "pk_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemonapp.pokemon",
                    ),
                ),
            ],
        ),
    ]
