# Generated by Django 4.1.5 on 2023-01-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemonapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
