# Generated by Django 4.1.5 on 2023-01-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemonapp", "0002_trainer_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="pokemon_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="trainer_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
